### ISSUE TITLE
Requirements ?

### ISSUE THREAD

**Issue by Archie2024** [rrpproxy/whmcs-rrpproxy-registrar#103]
From your documentation, I see that WHMCS requirements are WHMCS 7.6+ or 8.x ... but what about the PHP version?
Is PHP 7.2.34 fine?

**Comment by KaiSchwarz-cnic** [comment]
Hi @Archie2024,

actually we are with PHP 7.4, but we are working on making it PHP 7.3 ready and then, I expect it also to be compatible with 7.2. This will take some time, but should not take longer than ~1 month.

HTH
Kai

**Comment by Archie2024** [comment]
What's the last version compatible with php 7.2.34 ?
(I looked around in the history version in https://github.com/rrpproxy/whmcs-rrpproxy-registrar/releases?page=5, but was not able to find such info... )

**Comment by KaiSchwarz-cnic** [comment]
I don't recommend trying older versions out. There had been bugs in the initial versions. Basically the module has been developed for PHP 7.4. We are already on reviewing in direction of PHP 7.3 to make it available this year (will be released together with full restructuring/bundling and thus takes time).

You may give the RRPproxy Module that is shipped with WHMCS in the meanwhile a try. Maybe that one works with PHP 7.2.
We're just not aware of the stability & quality of that module. Bug reports regarding that module have to be addressed then of course to WHMCS.

There's actually nothing else we can do here.
