### ISSUE TITLE
cPanel whmcs module

### ISSUE THREAD

**Issue by jsjcjsjc** [rrpproxy/whmcs-rrpproxy-registrar#106]
Hi
You mentioned  that you have the CPanel module in the link below.
https://centralnic-reseller.github.io/centralnic-reseller/docs/rrpproxy/cpanel/#cpanel-integration

I am intereted in your cPanel whmcs module, could you please share it to me ?

BTY,  is ther Virtual Servers whmcs module ?
Thanks

**Comment by KaiSchwarz-cnic** [comment]
Hi @jsjcjsjc 

we have no Virtual Servers in Portfolio yet. This might change as we recently hired a Head of Mass Hosting.
Nothing else I can forward in that regard yet.

cPanel Module for WHMCS:
https://drive.google.com/file/d/1PsebaRWqmVOfEuOrsPHFg01r-9mueEVt/view?usp=sharing
I'll grant access as soon as possible after you requested access.

HTH

**Comment by KaiSchwarz-cnic** [comment]
@jsjcjsjc 
There's no documentation available for this module. It got handed over to my hands without further explanations.
We are not having experience with it on our end yet as well. PS: as you directly contacted me via email: We are not responding to direct emails. Support Cases have to be covered either via support system or via github issue.
Otherwise we allow people to by-pass the FCFS order.

**Comment by jsjcjsjc** [comment]
> There's no documentation available for this module. It got handed over to my hands without further explanations. We are not having experience with it on our end yet as well. PS: as you directly contacted me via email: We are not responding to direct emails. Support Cases have to be covered either via support system or via github issue. Otherwise we allow people to by-pass the FCFS order.
> 
> I had a short talk with the author. Copy the modules folder into your system, then switch to System Settings > Addons. Activate the Addon and Configure it (provide your rrp credentials there). The module hasn't been tested on our end. Bug reports, for now over this repository please.

Thank you so much ;-)

**Comment by jsjcjsjc** [comment]
> @jsjcjsjc There's no documentation available for this module. It got handed over to my hands without further explanations. We are not having experience with it on our end yet as well. PS: as you directly contacted me via email: We are not responding to direct emails. Support Cases have to be covered either via support system or via github issue. Otherwise we allow people to by-pass the FCFS order.
> 
> I had a short talk with the author. Copy the modules folder into your system, then switch to System Settings > Addons. Activate the Addon and Configure it (provide your rrp credentials there). The module hasn't been tested on our end. Bug reports, for now over this repository please.

Hi Kai
I am testing cPanel whmcs module, Can you tell me how to fill in this information ?
[![xkxMZQ.jpg](https://s1.ax1x.com/2022/09/23/xkxMZQ.jpg)](https://imgse.com/i/xkxMZQ)
