### ISSUE TITLE
TLD and Pricing synchronisation problem

### ISSUE THREAD

**Issue by jsjcjsjc** [rrpproxy/whmcs-rrpproxy-registrar#107]
OS: windows 11
Browser Microsoft Edge 105.0.1343.42
WHMCS Version 8.13 & 8.51
PHP Version 7.4
ISPAPI SSL Module Version RRP 1.7

Hi
regarding TLD and Pricing synchronisation in WHMCS, I find most time I have to sync with RRP sever more than two times after several testings.
even the sync process is successfull. there is still erroe in WHMCS log.
here is the error messages.
![PV0en.jpg](https://s1.328888.xyz/2022/10/04/PV0en.jpg)

**Comment by KaiSchwarz-cnic** [comment]
Thanks @jsjcjsjc let us see, if this can be improved.

**Comment by WenLiCG** [comment]
> > regarding TLD and Pricing synchronisation in WHMCS, I find most time I have to sync with RRP sever more than two times after several testings.
> 
> What's the reason for retrying? There API error messages you mentioned by screenshot? or is there any other reason that you haven't specified in this ticket yet?

Thanks
cloud you tell me where i can find the log information ?
the screen comes from  WHMCS module log

**Comment by KaiSchwarz-cnic** [comment]
> Thanks
> cloud you tell me where i can find the log information ?
> the screen comes from WHMCS module log

Exactly, the logs are from WHMCS Module Log.
Tool Icon > System Logs > Module Log

HTH

**Comment by WenLiCG** [comment]
> > Thanks
> > cloud you tell me where i can find the log information ?
> > the screen comes from WHMCS module log
> 
> Exactly, the logs are from WHMCS Module Log. Tool Icon > System Logs > Module Log
> 
> HTH

Yes,  the screen comes from Tool Icon > System Logs > Module Log, do you need more infromation ?

**Comment by WenLiCG** [comment]
> WenLiCG = jsjcjsjc ?

YES, WenLiCG = jsjcjsjc  :-)
Sorry, I have no idea. the only thing i can do is share the log, or could you tell me how to share more useful information to you ?

**Comment by KaiSchwarz-cnic** [comment]
That's already fine.

**Comment by SebastianVassiliou-cnic** [comment]
@jsjcjsjc / @WenLiCG you said you need to run the tld import 2-3 times. What happens on the first 1-2 tries? What is it that does not work?
I can confirm those errors in the module log happen, but they can be ignored, the import still works fine for me on first try, so I am not sure what to look for.

**Comment by KaiSchwarz-cnic** [comment]
Let me close this ticket. Sebastian pointed out that these errors in module log related to command GetZoneInfo can be ignored.
I've been asking the same question if there's anything else other than the errors already in this thread.

So @WenLiCG: No need to run your pricing import multiple times. Ignore those errors.

Still, thanks for reporting.
