### ISSUE TITLE
.eu domains can't be transferred

### ISSUE THREAD

**Issue by OrangeJuiced** [rrpproxy/whmcs-rrpproxy-registrar#108]
**Describe the bug**
Trying to transfer a .eu domain produces the following error: Invalid attribute name; X-EU-REGISTRANT-LANG. Worked around the issue by removing `$extensions['X-EU-REGISTRANT-LANG'] = "EN";` from `eu.php` in `keysystems/tlds` temporarily.

**Comment by KaiSchwarz-cnic** [comment]
@OrangeJuiced thanks for reporting. I assigned this task to the responsible developer in my team. this will be patched in our new software bundle repository: https://github.com/centralnicgroup-opensource/rtldev-middleware-whmcs
This means, that a migration is necessary, we don't maintain our rrpproxy and ispapi repositories any longer in favour of this software bundle.

We'll keep you in the loop and we'll point you on the upgrade steps when patched.

Best
Kai

**Comment by SebastianVassiliou-cnic** [comment]
This issue was fixed in v16.2.4 of our new centralnic repo, see https://github.com/centralnicgroup-opensource/rtldev-middleware-whmcs/releases
