### ISSUE TITLE
wrong X-ACCEPT-QUARANTINE for .eu domains

### ISSUE THREAD

**Issue by Remitur** [rrpproxy/whmcs-rrpproxy-registrar#28]
In modules/registrars/keysystems/tlds/eu.php ( https://github.com/rrpproxy/whmcs-rrpproxy-registrar/blob/master/modules/registrars/keysystems/tlds/eu.php 9 you can find this:

`$extensions['X-ACCEPT-QUARANTINE'] = "1";`

But:

- X-ACCEPT-QUARANTINE parameter is used only for domain transfer from quarantine (https://wiki.rrpproxy.net/domains/tlds/eu)

- using it during, i.e., domain registration causes an error:
`Array
(
    [code] => 503
    [description] => Invalid attribute name; X-ACCEPT-QUARANTINE
)`

I guess the fix is easy (just remove it from code...), but I'm wondering if there's any other reason I'm missing about this parameters being specified...

**Comment by h9k** [comment]
Thanks for reporting this, @Remitur.
You are correct, that parameter does not belong there.
I will proceed to fix this right away.

**Comment by h9k** [comment]
Fixed in version 0.4.4
