### ISSUE TITLE
.EU domain transfer wrongly managed

### ISSUE THREAD

**Issue by Remitur** [rrpproxy/whmcs-rrpproxy-registrar#38]
The module manages .eu domain transfer as "simple transfer", while RRPPROXY system requires a transfer-trade operation.

If you try a .eu domain transfer, you get a "_Missing required attribute; OWNERCONTACT0 required_" error.

The module instead should:
- create a new contact handle
- specify the contact handle in the transfer command

**Comment by papakai** [comment]
@Remitur thanks for reporting, we will care about this tomorrow.

**Comment by h9k** [comment]
I believe I fixed the issue, but I did not have time to test yet. So I created a draft pull request for time being.
It includes some refactoring related to contact handling.
As soon as I tested it successfully, the PR will be merged.
