### ISSUE TITLE
error in DNS Management

### ISSUE THREAD

**Issue by jsjcjsjc** [rrpproxy/whmcs-rrpproxy-registrar#55]
**Describe the bug**

**To Reproduce**
1.buy a domain
2.domain-> my domain -> click domain ->DNS Management
3. See error
4. ![avatar](https://s3.jpg.cm/2021/08/28/IH6joh.png)

**Expected behavior**

**Context (please complete the following information):**
 - WHMCS Version [8.1.3]
 - PHP Version [7.4]
 - ISPAPI Registrar Module Version [0.8.4]

**Comment by h9k** [comment]
You wrote you use the ISPAPI registrar module, yet this is the repository for the RRPproxy (keysystems) module.
Version 0.8.4 suggests you are using the latter. Can you please confirm?

**Comment by papakai** [comment]
Hi @jsjcjsjc and welcome,

nice to see you using the rrpproxy registrar module.

> A clear and concise description of what the bug is.

Welcome to the world of WHMCS. Some registrar function really allow returning a custom error output, and for the most ones WHMCS also displays the exact returned error message. But in this case (for the underlying `GetDNS` function), it is not the case - you're just getting this generic error message shown. Which is just bad when it comes to Customer Support.

So, again, this isn't basically something that WHMCS supports / allows in this section.
To further support you, we would need further details.

Please open a support ticket by just sending a mail to help@hexonet.support. Don't wonder, we at hexonet cover the whmcs development and support for the HEXONET/ispapi and RRPproxy/keysystems WHMCS modules. Please provide in that mail you user account in the RRPproxy System and the affected domain name for reference.

**Comment by papakai** [comment]
Hey Mr.X / jsjcjsjc,

Please upgrade, @h9k fixed the DNS Management.

HTH
Kai

**Comment by jsjcjsjc** [comment]
hello, I am useing WHMCS 8.4 and RRP 1.0.2
the problem arise again
could you please help me to check it again ?
Thanks

**Comment by papakai** [comment]
@h9k please investigate :-)

**Comment by h9k** [comment]
Unable to reproduce. It works fine. Fresh domain got DNS zone created properly, adding and deleting records is also possible.
If you still have issues, it might be something else. Please open a new issue instead and provide us with a fresh screenshot. Also, please enable Module Logging in WHMCS and provide us what is logged when accessing the DNS Management function.
