### ISSUE TITLE
additional fields in domain transfer

### ISSUE THREAD

**Issue by Remitur** [rrpproxy/whmcs-rrpproxy-registrar#56]
AFAIU, the module for domain transfer right now does not use the contacts defined in WHMCS, and neither special domain fields (if any) (but for  X-EU-REGISTRANT-CITIZENSHIP for .eu domains)

So the module works just and only for those extensions that for transfer do not require anything but domain name and authinfo, and any other transfer operation give some kind of error and need to be processed manually.

So, here I'm to ask: any ETA for its feature to be implemented?
(BTW: this function is rightly implemented in your ISPAPI module; any willing, in the future, to create and maintain a single WHMCS module for both, ISPAPI and RRPPROXY?)

`function keysystems_TransferDomain($params)
{
    try {
        $api = new RRPProxyClient($params);
        if ($params['tld'] == 'eu') {
            $contact_id = $api->getOrCreateOwnerContact($params);

            $data = [
                'domain' => $params['domainname'],
                'auth' => $params['eppcode'],
                'action' => 'request',
                'ownercontact0' => $contact_id,
                'FORCEREQUEST' => 1
            ];

            $extensions = [];
            $extensions_path = implode(DIRECTORY_SEPARATOR, [__DIR__, "tlds", "eu.php"]);
            if (file_exists($extensions_path)) {
                require_once $extensions_path;
                if (@$extensions['X-EU-REGISTRANT-CITIZENSHIP']) {
                    $data['X-EU-REGISTRANT-CITIZENSHIP'] = $extensions['X-EU-REGISTRANT-CITIZENSHIP'];
                }
            }

            $api->call('TransferDomain', $data);
        } else {
            $api->call('TransferDomain', [
                'domain' => $params['domainname'],
                'auth' => $params['eppcode'],
                'FORCEREQUEST' => 1
            ]);
        }
        return ['success' => true];
    } catch (Exception $e) {
        return ['error' => $e->getMessage()];
    }
}`

**Comment by papakai** [comment]
Hey @Remitur,

Thanks for reporting. I can forward that I am already working on a module merge. Still, this issue has to be deeply analyzed, additional fields will be fully compatible in future. Actually there could still be differences on API Level. Getting the reported issues fixed earlier is of highest interest for us, as of the merge will take a while.

Best
Kai

**Comment by papakai** [comment]
This issue has been handed over to @h9k to get fixed as far as possible atm.

**Comment by papakai** [comment]
@Remitur

@h9k has been working on getting this matter improved. Closing. Again, thanks for addressing.
