### ISSUE TITLE
could you please show me the API server adress of whmcs-rrpproxy-registrar

### ISSUE THREAD

**Issue by jsjcjsjc** [rrpproxy/whmcs-rrpproxy-registrar#62]
Hi
I'd like to builder a reserller website close to whmcs-rrpproxy-registrar
could you please show me the API server adress of whmcs-rrpproxy-registrar
Thanks

**Comment by papakai** [comment]
Not sure what you're exactly looking for, but the below might help...

https://github.com/rrpproxy/whmcs-rrpproxy-registrar/blob/master/modules/registrars/keysystems/lib/RRPProxyClient.php#L42-L46

So either `https://api-ote.rrpproxy.net` (OT&E, Demo System) or `https://api.rrpproxy.net` (LIVE / real-world System) as hostname. 

https://www.rrpproxy.net/deutsch/API/HTTPS-Socket

HTH
