### ISSUE TITLE
rrpproxy role user 

### ISSUE THREAD

**Issue by jsjcjsjc** [rrpproxy/whmcs-rrpproxy-registrar#85]
Hi
I try to create a role user only dedicated for WHMCS as the lik below.
https://centralnic-reseller.github.io/centralnic-reseller/docs/rrpproxy/whmcs/whmcs-rrpproxy-registrar/#restrictive-user-role

But it looks like there is a problem if didn't ebable "Rights required for webinterface usage" in the pictures below
it will display a error message "RRPproxy v1.3.2: QueryZoneList - Authorization failed; Access denied for class: TOOL and type: STATUS".
 so i have to enable "Rights required for webinterface usage" ?
[![LCEURf.jpg](https://s1.ax1x.com/2022/04/08/LCEURf.jpg)](https://imgtu.com/i/LCEURf)

**Comment by papakai** [comment]
Let me link this issue to #78 as it is related.

**Comment by papakai** [comment]
Yes, please activate this switch button. I'll be updating our docs when you've provided the feedback for #78.

**Comment by jsjcjsjc** [comment]
> Yes, please activate this switch button. I'll be updating our docs when you've provided the feedback for #78.

Thanks for your quick response, is it possible disable webinterface ? only for API ?

**Comment by KaiSchwarz-cnic** [comment]
@jsjcjsjc sorry for the delay - no idea regarding this question. that's something you would have to forward via ticket to the support team.
