### ISSUE TITLE
.be domains can't be renewed

### ISSUE THREAD

**Issue by OrangeJuiced** [rrpproxy/whmcs-rrpproxy-registrar#95]
**Describe the bug**
The .be TLD does not support explicit renewal (https://wiki.rrpproxy.net/domains/tlds/be). However, the support_renewals column value in the mod_rrpproxy_zones table for .be is set to 1. This breaks .be domain renewal in WHMCS producing the following error: `Invalid attribute value; explicit renewals not allowed for this TLD; please set domain to AUTORENEW or RENEWONCE`. The support_renewals column value for .be should be changed to 0 to resolve the issue.

**Comment by KaiSchwarz-cnic** [comment]
@OrangeJuiced thanks for forwarding. I'll assign it to the responsible dev in my team.

**Comment by h9k** [comment]
Thanks for reporting. There was an issue with how support_renewals value was determined for some tlds, notably .be and .at were affected, probably a few others.
Should be fixed in version 1.5.1
